Repository LikeLion-at-DGU/2025_fall_festival_BE, pull requests merged in 2025-09, with the labels that each got.

#28 ✨ Feat: 주/야간(디오더여부)부스 상세페이지 구현(#2)
  booth/models.py
  booth/selectors.py
  booth/serializers.py
  booth/views.py
Labels: Feat

#44 [Feat] 관리자 UID 로그인/검증/로그아웃 API 구현
  adminuser/authentication.py
  adminuser/permissions.py
  adminuser/services.py
  adminuser/urls.py
  adminuser/views.py
  event/migrations/0001_initial.py
  project/settings.py
  project/urls.py
  requirements.txt
Labels: Feat

#81 [Feat] model str 문 추가 및 admin.py 수정
  adminuser/models.py
  board/admin.py
  board/models.py
  booth/admin.py
  booth/models.py
  common/admin.py
  game/admin.py
  game/models.py
Labels: Feat

#83 [fix]: event 폴더 삭제
  event/migrations/0001_initial.py
Labels: Fix

#84 [Fix] booth str 문 수정
  booth/models.py
Labels: Fix

#85 [Refac] booth str 문 주석처리
  booth/models.py
Labels: Refactor

#86 [Refac] 어드민 모델 str 예외처리
  adminuser/models.py
Labels: Refactor

#100 🐛 Fix: serializer context 보강(#98)
  booth/serializers.py
  booth/views.py
Labels: Fix

#126 [Fix] booth model 변수 필드 null 값 허용
  booth/models.py
Labels: Fix

#133 [Fix] 이벤트 게시글 celery 로직으로 수정
  adminuser/migrations/0001_initial.py
  adminuser/migrations/0002_alter_admin_role.py
  adminuser/migrations/0003_admin_uid_admin_uid_expires_at.py
  adminuser/migrations/0004_remove_admin_uid_remove_admin_uid_expires_at_and_more.py
  adminuser/tasks.py
  board/migrations/0001_initial.py
  board/migrations/0002_board_writer_alter_boothevent_end_time_and_more.py
  board/tasks.py
  booth/dorders.py
  booth/migrations/0001_initial.py
  booth/migrations/0002_booth_like_cnt.py
  booth/migrations/0003_remove_booth_like_cnt_remove_booth_operate_date.py
  booth/migrations/0004_booth_like_cnt.py
  booth/migrations/0005_alter_booth_image_url.py
  booth/migrations/0006_alter_menu_image_url.py
  common/migrations/0001_initial.py
  game/migrations/0001_initial.py
  project/settings.py
  stage/migrations/0001_initial.py
  stage/migrations/0002_stage_type.py
Labels: Fix

#166 🐛 fix: 좋아요 개수가 300개를 초과할 경우 추가 불가 처리
  booth/views.py
Labels: Fix
